version: 2
updates:
- package-ecosystem: github-actions
  directory: /.github/workflows/
  target-branch: development
  schedule:
    interval: weekly
  groups:
    github-actions:
      patterns:
        - "*"
