name: update
run-name: Rebuild snap and update release
inputs:
  tag:
    required: false
    type: string
  channel:
    required: false
    type: string
  update:
    required: false
    type: boolean
    default: false
runs:
  using: composite
  steps:
  - uses: actions/download-artifact@v4
    with:
      pattern: "*.snap"
      merge-multiple: true
  - name: create new release
    if: ${{ inputs.update == 'false' }}
    uses: ncipollo/release-action@v1
    with:
      tag: ${{ inputs.tag }}
      bodyFile: RELEASE.md
      artifacts: "${{ github.workspace }}/*.snap"
      prerelease: ${{ inputs.channel != 'stable' }}
      makeLatest: true
      skipIfReleaseExists: true
      artifactErrorsFailBuild: true
  - name: update existing release
    if: ${{ inputs.update == 'true' }}
    uses: ncipollo/release-action@v1
    with:
      tag: ${{ inputs.tag }}
      artifacts: "${{ github.workspace }}/*.snap"
      allowUpdates: true
      replacesArtifacts: true
      omitNameDuringUpdate: true
      omitBodyDuringUpdate: true
      omitPrereleaseDuringUpdate: true
      omitDraftDuringUpdate: true
      artifactErrorsFailBuild: true
