name: ⚠️ Vulnerability
description: Use this to report a vulnerability or other security issue
labels: ["security"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Description
    description: A detailed description of the security issue and what needs to be done to fix it.
    render: markdown
  validations:
    required: true
- type: dropdown
  attributes:
    label: Severity
    description: How serious is the problem?
    options:
      - Low
      - Medium
      - High
      - Critical
    default: 0
- type: textarea
  attributes:
    label: Dependencies
    description: Which dependencies are involved?
  validations:
    required: false
