name: 🚀 Feature Request
description: Use this if you want to suggest an idea or improvement
labels: ["enhancement"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing request for this?
    description: Please search to see if an issue already exists for the feature you want.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Description
    description: A detailed description of what you're missing and why it should be added.
  validations:
    required: true
