name: rebuild
run-name: Rebuild snap and update release
inputs:
  tag:
    required: true
    type: string
  release:
    required: false
    type: string
  publish:
    required: false
    type: boolean
  SNAPCRAFT_STORE_CREDENTIALS:
    required: false
    type: string
runs:
  using: composite
  steps:
  - uses: actions/checkout@v4
  - uses: ./.github/actions/build
    with:
      tag: ${{ inputs.tag }}
    id: build
  - uses: ncipollo/release-action@v1
    with:
      tag: ${{ inputs.tag }}
      artifacts: ${{ steps.build.outputs.snap }}
      allowUpdates: true
      replacesArtifacts: true
      omitNameDuringUpdate: true
      omitBodyDuringUpdate: true
      omitPrereleaseDuringUpdate: true
      omitDraftDuringUpdate: true
      artifactErrorsFailBuild: true
  - uses: snapcore/action-publish@v1
    if: ${{ inputs.publish == 'true' }}
    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ inputs.SNAPCRAFT_STORE_CREDENTIALS }}
    with:
      snap: ${{ steps.build.outputs.snap }}
      release: ${{ inputs.release || 'latest/edge' }}
