name: update
run-name: Rebuild snap and update release
inputs:
  release_tag:
    required: true
    type: string
jobs:
  rebuild-and-update-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/snapcraft
      id: snapcraft
    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ inputs.release_tag }}
        artifacts: ${{ steps.snapcraft.outputs.snap }}
        allowUpdates: true
        replacesArtifacts: true
        omitNameDuringUpdate: true
        omitBodyDuringUpdate: true
        omitPrereleaseDuringUpdate: true
        omitDraftDuringUpdate: true
        artifactErrorsFailBuild: true
