name: scan
run-name: Scan snap for vulnerabilities
inputs:
  snap:
    required: true
    type: string
runs:
  using: composite
  steps:
  - uses: actions/download-artifact@v4
    with:
      name: ${{ inputs.snap }}
  - name: install syft
    shell: bash
    run: sudo snap install syft --classic
  - name: generate SBOM
    shell: bash
    run: |
      syft snap:${{ inputs.snap }} -o json > sbom.min.json
      jq "." sbom.min.json > sbom.json
  - uses: actions/upload-artifact@v4
    with:
      name: sbom.json
      path: sbom.json
      retention-days: 1
      overwrite: true
  - name: install grype
    shell: bash
    run: sudo snap install grype --classic
  - name: scan SBOM
    shell: bash
    run: |
      grype sbom:sbom.json --distro ubuntu:24.04 -o json > vulnerabilities.min.json
      jq "
        def severity_weight:
          if .vulnerability.severity == 'Critical' then 5
          elif .vulnerability.severity == 'High' then 4
          elif .vulnerability.severity == 'Medium' then 3
          elif .vulnerability.severity == 'Low' then 2
          else 1 end;
          .matches |= sort_by(- (severity_weight))
        " vulnerabilities.min.json > vulnerabilities.json
  - uses: actions/upload-artifact@v4
    with:
      name: vulnerabilities.json
      path: vulnerabilities.json
      retention-days: 1
      overwrite: true
  - name: print vulnerabilities
    shell: bash
    run: |
      vulnerabilities=$(jq -r ".matches[].vulnerability.id" vulnerabilities.json)
      if [ -z "$vulnerabilities" ]; then
        echo No vulnerabilities found
      else
        echo Vulnerabilities:
        for v in $vulnerabilities; do
          echo "::group::$v"
          cat vulnerabilities.json | grype explain -q --id $v
          echo "::endgroup::"
        done
      fi
