name: build
run-name: Build snap
on:
  push:
    paths:
    - 'snap/**'
    - 'src/**'
    - '!**.md'
  pull_request:
    paths:
    - 'snap/**'
    - 'src/**'
    - '!**.md'
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
        required: true
        default: warning
        type: choice
        options:
        - info
        - warning
        - debug
jobs:
  build:
    if: ${{ !startsWith(github.ref, 'refs/tags') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build
      id: build
    - uses: ./.github/actions/test
      with:
        snap: ${{ steps.build.outputs.snap }}
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.build.outputs.snap }}
        path: ${{ steps.build.outputs.snap }}
