name: build
run-name: Build snap
on:
  push:
    branches:
    - development
    paths:
    - 'snap/**'
    - 'src/**'
    - '!**.md'
  pull_request:
    paths:
    - 'snap/**'
    - 'src/**'
    - '!**.md'
  workflow_dispatch:
    inputs:
      test:
        description: Run tests
        required: true
        type: boolean
        default: true
jobs:
  build:
    if: ${{ !startsWith(github.ref, 'refs/tags') }}
    runs-on: ${{ matrix.builder }}
    strategy:
      matrix:
        include:
          - builder: ubuntu-latest
            arch: amd64
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build
      id: build
    - run: echo "${{ matrix.arch }}=${{ steps.build.outputs.snap }}" >> $GITHUB_OUTPUT
      id: snap
    outputs:
      amd64: ${{ steps.snap.outputs.amd64 }}
  test:
    needs: build
    runs-on: ${{ matrix.builder }}
    strategy:
      matrix:
        include:
          - builder: ubuntu-latest
            arch: amd64
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/test
      with:
        snap: ${{ needs.build.outputs[matrix.arch] }}
