name: build
run-name: Build snap
on: [push, pull_request]
jobs:
  build:
    if: ${{ !startsWith(github.ref, 'refs/tags') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: snapcore/action-build@v1
      id: snapcraft
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.snapcraft.outputs.snap }}
        path: ${{ steps.snapcraft.outputs.snap }}
    - name: Test installation
      run: |
        sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}
        sudo snap set mastodon-server domain="localhost"
        sudo snap set mastodon-server email="admin@local.host"
        sudo mastodon-server.setup
