name: update
run-name: Rebuild snap and update release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag
        required: true
        type: string
      channel:
        description: Channel
        required: true
        type: choice
        default: stable
        options:
        - stable
        - candidate
        - beta
        - edge
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
jobs:
  rebuild:
    runs-on: ${{ matrix.builder }}
    strategy:
      matrix:
        include:
          - builder: ubuntu-latest
            arch: amd64
    steps:
    - uses: kaisugi/action-regex-match@v1.0.1
      with:
        text: ${{ github.ref_name }}
        regex: '^[\d\.]+snap\d+(candidate|beta|edge|)\d*$'
      id: regex
    - uses: actions/checkout@v4
    - uses: ./.github/actions/rebuild
      with:
        tag: ${{ inputs.tag }}
      id: rebuild
    - uses: ./.github/actions/publish
      with:
        snap: ${{ steps.rebuild.outputs.snap }}
        channel: ${{ inputs.channel || steps.regex.outputs.group1 }}
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
