#!/bin/bash -e

. "$SNAP/debug.env"

trap end_debug_log EXIT
begin_debug_log post-refresh

. "$SNAP/snap.env"

set_default_settings

export PREVIOUS_SNAP_VERSION="$(get_snap_version_file)"

echo Set permissions on log dir
fix_daemon_user "$LOG_DIR"

echo Set permissions on secret dir
if [ -d "$SECRET_DIR" ]; then
    chmod -f 750 "$SECRET_DIR" || true
    chmod -fR 640 $SECRET_DIR/* || true
    chown -fR root:$DAEMON_USER --no-dereference "$SECRET_DIR" || true
fi

# NOTE: This is a fix for versions < 4.4.5snap2 and should be removed in the future
snapctl unset update.backup
snapctl unset update.backups

# NOTE: This is a fix for versions < 4.5.3snap3 and should be removed in the future
if SYSTEM_PREVIOUS_REVISION=$(snapctl get snap.previous-revision); then
    if ! [ -z "$SYSTEM_PREVIOUS_REVISION" ]; then
        snapctl set snap.previous-revision="$SYSTEM_PREVIOUS_REVISION"
        snapctl unset snap.previous-revision
    fi
fi
if SYSTEM_ANNOUNCEMENT_ID=$(snapctl get snap.announcement-id); then
    if ! [ -z "$SYSTEM_ANNOUNCEMENT_ID" ]; then
        snapctl set snap.announcement-id="$SYSTEM_ANNOUNCEMENT_ID"
        snapctl unset snap.announcement-id
    fi
fi
if SYSTEM_COMPILATION_REQUIRED=$(snapctl get snap.compilation-required); then
    if ! [ -z "$SYSTEM_COMPILATION_REQUIRED" ]; then
        snapctl set snap.complation-required="$SYSTEM_COMPILATION_REQUIRED"
        snapctl unset snap.compilation-required
    fi
fi
if SYSTEM_RESTART_REQUIRED=$(snapctl get system.restart-required); then
    if ! [ -z "$SYSTEM_RESTART_REQUIRED" ]; then
        snapctl set services.backend.restart-required=$(snapctl get system.restart-required.backend)
        snapctl unset system.restart-required.backend
        snapctl set services.nginx.restart-required=$(snapctl get system.restart-required.nginx)
        snapctl unset system.restart-required.nginx
        snapctl set services.pgbouncer.restart-required=$(snapctl get system.restart-required.pgbouncer)
        snapctl unset system.restart-required.pgbouncer
        snapctl set services.postgres.restart-required=$(snapctl get system.restart-required.postgres)
        snapctl unset system.restart-required.postgres
        snapctl set services.redis.restart-required=$(snapctl get system.restart-required.redis)
        snapctl unset system.restart-required.redis
        snapctl set services.sidekiq.restart-required=$(snapctl get system.restart-required.sidekiq)
        snapctl unset system.restart-required.sidekiq
        snapctl set services.streaming.restart-required=$(snapctl get system.restart-required.streaming)
        snapctl unset system.restart-required.streaming
    fi
fi

# Postgres

. "$SNAP/postgres.env"

echo Set permissions on postgres files and dirs
fix_daemon_user "$PG_HOME"
fix_daemon_user "$PG_SOCK_DIR"
fix_daemon_user "$PG_LOG_FILE"
# NOTE: Permissions must be fixed each time the postgres data dir has been moved
if [ -d "$PG_DATA" ]; then
    run_as_daemon_user chmod 700 "$PG_DATA" -R
fi

echo Update postgres config
copy_postgres_config
enable_postgres_config

# Pgbouncer

. "$SNAP/pgbouncer.env"

# NOTE: This is a fix for versions < 4.5.3snap3 and should be removed in the future
mkdir_for_daemon_user "$PGB_HOME"

echo Set permissions on pgbouncer files and dirs
fix_daemon_user "$PGB_HOME"
fix_daemon_user "$PGB_SOCK_DIR"
fix_daemon_user "$PGB_LOG_FILE"

echo Update pgbouncer config
copy_pgbouncer_config

# Redis

. "$SNAP/redis.env"

echo Set permissions on redis files and dirs
fix_daemon_user "$REDIS_HOME"
fix_daemon_user "$SOCK_DIR/redis.sock"
fix_daemon_user "$LOG_DIR/redis.log"

echo Update redis config
copy_config_as_daemon_user redis redis.conf

# Mastodon

. "$SNAP/mastodon.env"

echo Set permissions on mastodon files and dirs
fix_daemon_user "$MASTODON_HOME"
fix_daemon_user "$LOG_DIR/backend.log"
fix_daemon_user "$LOG_DIR/streaming.log"
fix_daemon_user "$LOG_DIR/sidekiq.log"
if [ "$(get_owner $MEDIA_DIR)" != "$DAEMON_USER" ]; then
    fix_daemon_user_media_dir
fi

# NOTE: This is a fix for versions <= 4.4.6snap1 and should be removed in the future
if UPDATE_ANNOUNCEMENT="$(snapctl get update.announcement)"; then
    if ! [ -z "$UPDATE_ANNOUNCEMENT" ]; then
        snapctl set announcement.pre-refresh="$UPDATE_ANNOUNCEMENT"
        snapctl set announcement.post-refresh="$UPDATE_ANNOUNCEMENT"
    fi
    snapctl unset update.announcement
fi

if [ "$SNAP_VERSION" != "$PREVIOUS_SNAP_VERSION" ]; then
    echo Update mastodon
    copy_mastodon_server_config
    update_mastodon_files

    if mastodon_config_exists; then
        echo Update mastodon config
        upgrade_mastodon_config
    fi
fi

# Nginx

. "$SNAP/nginx.env"

echo Set permissions on nginx files and dirs
fix_daemon_user "$NGINX_HOME"
fix_daemon_user "$SNAP_COMMON/.well-known"
fix_daemon_user "$NGINX_CACHE"
fix_daemon_user "$NGINX_LOG_FILE"
fix_daemon_user "$NGINX_ACCESS_LOG_FILE"

# NOTE: This is a fix for older versions and may be removed in the future
if ! is_access_log_format "$(snapctl get log.access.format)"; then
    snapctl set log.access.format="network"
fi

echo Update nginx configs
copy_nginx_configs

# Acme

echo Set permissions on acme dir
fix_daemon_user "$ACME_HOME"

# Logrotate

echo Update logrotate config
copy_config logrotate logrotate.conf
