#!/bin/bash -e

. "$SNAP/snap.env"
. "$SNAP/postgres.env"

if $UPDATE_BACKUPS; then
    SKIP_MEDIA_EXPORT=true $SNAP/bin/export "$UPDATE_BACKUP_DIR"
fi

echo Create postgres backup
pg_dumpall.wrapper -f "$SNAP_COMMON/database.sql"
