#!/bin/bash -e

. "$SNAP/snap.env"
. "$SNAP/postgres.env"
. "$SNAP/mastodon.env"
. "$SNAP/debug.env"

begin_debug pre-refresh
trap end_debug EXIT

update_postgres_version_file

pre_refresh_tasks_required

if $UPDATE_ANNOUNCEMENT; then
    echo Add update announcement
    if ANNOUNCEMENT_ID=$(mastodon_publish_announcement "The server will be updated in 3 minutes and will be unavailable for a short time"); then
        snapctl set system.announcement-id="$ANNOUNCEMENT_ID"
        snapctl restart "$SNAP_NAME.sidekiq"
        sleep 180
    fi
fi
